blog/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = "blog"
urlpatterns = [
    url(r'^$', views.home, name = 'home_page_view'),
    path('page/<int:page>', views.home, name = 'home_page_view'),
    url(r'^blog/(?P<slug>[\w-]+)/$(?i)', views.detail, name = 'detail_post_view'),
    url(r'^category/(?P<slug>[\w]+)/$(?i)', views.category, name = 'category_view'),
    path('category/<slug:slug>/page/<int:page>', views.category, name = 'category_view'),
]

redblog/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url('', include('blog.urls')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils import timezone
from extentions.utils import jalali_converter

#my managers
#models.manager yani az on ers bari kon va 
#yeseri chiza behesh ezafe kon
class ArticleManager(models.Manager):
    def published(self):
        return self.filter(status = 'p')

class Category(models.Model):
    title = models.CharField(max_length = 200, verbose_name = 'عنوان دسته‌بندی')
    slug = models.SlugField(max_length = 100, unique = True, verbose_name = 'آدرس دسته‌بنده')

    class Meta:
        verbose_name = "دسته‌بندی"
        verbose_name_plural = "دسته‌بندی‌ها"

    def __str__(self):
        return self.title

class Article(models.Model):
    STATUS_CHOICES = [
        ('d', 'پیش‌نویس'),
        ('p', 'منتشر شده')
    ]
    title = models.CharField(max_length = 200, verbose_name = 'عنوان مقاله')
    slug = models.SlugField(max_length = 100, unique = True, verbose_name = 'آدرس مقاله')
    category = models.ManyToManyField(Category, verbose_name = 'دسته‌بندی', related_name = "articles")
    content = models.TextField(verbose_name = 'محتوا')
    thumbnail = models.ImageField(upload_to = 'thumbnail', verbose_name = 'تصویر بندانگشتی')
    published = models.DateTimeField(default = timezone.now, verbose_name = 'زمان انتشار')
    created = models.DateTimeField(auto_now_add = True)
    updated = models.DateTimeField(auto_now_add = True)
    status = models.CharField(max_length = 1, choices = STATUS_CHOICES, verbose_name = 'وضعیت')

    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقالات"

    def __str__(self):
        return self.title

    def jpublished(self):
        return jalali_converter(self.published)
    
    objects = ArticleManager()

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article, Category
from django.core.paginator import Paginator


def home(request, page = 1):
    article_list = Article.objects.published()
    paginator = Paginator(article_list, 1)
    articles = paginator.get_page(page)
    context = {
        'articles' : articles,
    }
    return render(request, 'home.html', context)

def detail(request, slug):
    context = {
        'article' : get_object_or_404(Article.objects.published(), status = 'p', slug = slug)
    }
    return render(request, 'detail.html', context)

def category(request, slug, page = 1):
    category = get_object_or_404(Category, slug = slug)
    article_list = category.articles.published()
    paginator = Paginator(article_list, 1)
    articles = paginator.get_page(page)
    context = {
        'category' : category,
        'articles' : articles,
    }
    return render(request, 'category.html', context)

blog/templates/category.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% title %}</title>
</head>
<body>
    <h3>{{ category.title }}</h3>
    {% for article in articles %}
        <a href="{{article.slug}}">{{article.title}}</a>
        <small> {{article.jpublished}} </small>
        <article> {{article.content|truncatechars:200|linebreaks}} </article>
        <br>
    {% endfor %}    

    <ul>
        {% if articles.has_next %}
        <li><a href="{% url 'blog:category_view' category.slug articles.next_page_number %}">پست های قبلی</a></li>
        {% endif %}
        {% if articles.has_previous %}
        <li><a href="{% url 'blog:category_view' category.slug articles.previous_page_number %}">پست های جدید</a></li>
        {% endif %}
    </ul>
</body>
</html>

blog/templates/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {{article.content}}
</body>
</html>

blog/templates/home.html
{% load static %}
{% load base_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% title %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
    {% for article in articles %}
        <a href="{{article.slug}}">{{article.title}}</a>
        <small> {{article.jpublished}} </small>
        <article> {{article.content|truncatechars:200|linebreaks}} </article>
        {% for cat in article.category.all %}
            <a href="{% url 'blog:category_view' cat.slug %}">{{ cat.title }}</a>
        {% endfor %}
        <br>
    {% endfor %}

    <ul>
        {% if articles.has_next %}
        <li><a href="{% url 'blog:home_page_view' articles.next_page_number %}">پست های قبلی</a></li>
        {% endif %}
        {% if articles.has_previous %}
        <li><a href="{% url 'blog:home_page_view' articles.previous_page_number %}">پست های جدید</a></li>
        {% endif %}
    </ul>

    {% category_nav %}
</body>
</html>

blog/templates/nav.html
salam jojo talaiii

{% for category in categories %}
    <p> {{ category }} </p>
{% endfor %}